### ISSUE TITLE
Kali linux : every scan aborted since last update - ospd-openvas error

### ISSUE THREAD

**Issue by Chridolc** [greenbone/ospd-openvas#799]
Hello.
Since last update on kali (system and greenbone components), every scan are automatically aborted after ashort period of activity.
ospd.openvas.log report this : 

OSPD[1841762] 2022-10-26 14:12:06,550: INFO: (ospd.command.command) Scan cb56381e-60fb-4dcf-b9d7-c9fe61a255a6 added to the queue in position 1.
OSPD[1841762] 2022-10-26 14:12:12,013: INFO: (ospd.ospd) Currently 1 queued scans.
OSPD[1841762] 2022-10-26 14:12:12,397: INFO: (ospd.ospd) Starting scan cb56381e-60fb-4dcf-b9d7-c9fe61a255a6.
OSPD[1841762] 2022-10-26 14:22:39,614: ERROR: (ospd.ospd) While handling client command:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/managers.py", line 810, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ospd/ospd.py", line 484, in handle_client_stream
    self.handle_command(data, stream)
  File "/usr/lib/python3/dist-packages/ospd/ospd.py", line 1223, in handle_command
    response = command.handle_xml(tree)
  File "/usr/lib/python3/dist-packages/ospd/command/command.py", line 453, in handle_xml
    self._daemon.check_scan_process(scan_id)
  File "/usr/lib/python3/dist-packages/ospd/ospd.py", line 1448, in check_scan_process
    status = self.get_scan_status(scan_id)
  File "/usr/lib/python3/dist-packages/ospd/ospd.py", line 670, in get_scan_status
    status = self.scan_collection.get_status(scan_id)
  File "/usr/lib/python3/dist-packages/ospd/scan.py", line 358, in get_status
    status = self.scans_table[scan_id].get('status')
  File "<string>", line 2, in get
  File "/usr/lib/python3.10/multiprocessing/managers.py", line 814, in _callmethod
    self._connect()
  File "/usr/lib/python3.10/multiprocessing/managers.py", line 801, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 507, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 635, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
OSPD[1841762] 2022-10-26 14:22:40,428: WARNING: (ospd.ospd) Error sending data to the cli                                                                                                ent while executing a scan cb56381e-60fb-4dcf-b9d7-c9fe61a255a6.
OSPD[1866096] 2022-10-26 14:25:38,841: INFO: (ospd.main) Starting OSPd OpenVAS version 21                                                                                                .4.5.dev1.

Dont't know if related, but all the memory is occupied by Redis (8 gb + 3gb of swap) (openvas running, but no scan runnin)  and a /24 "normal" scan use 100% of CPU.

Thanks
![gvm02](https://user-images.githubusercontent.com/89592720/198034056-5a61bdb9-fd77-424c-a6a7-535946184fff.png)
![gvm01](https://user-images.githubusercontent.com/89592720/198034067-98109d83-ef4b-4dd9-aaa9-043ebc51fa56.png)

**Comment by Chridolc** [comment]
Hello.
Every update are done via apt-get under Kali.
i think that the problem was solved : caused by a malfunction with redis,
which have created 12gb of RDB files. The content was loaded at startup and
caused crashes (memory full, heavy swap R/W... Removing these files seems
to have solved the problem. We are currently stressing the scanner with
large network scans.
22.04 is not yet available under kali (sadly) yet...

Thanks.

Le jeu. 27 oct. 2022 à 15:34, Juan José Nicola ***@***.***> a
écrit :

**Comment by jjnicola** [comment]
Hi @Chridolc ,
I am glad to read that you found the issue. You can disable the RDB snapshots via config file in the redis.conf, to avoid this issue happening again.
Best Regards,
